# Generated by Django 4.0.6 on 2022-08-22 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='Заголовок H1')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('article_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('article_slug', models.CharField(default='article2022-08-22 21:10:04.395478', max_length=200, verbose_name='URL')),
                ('article_short_desc', models.TextField(blank=True, verbose_name='Короткое описание для Schema')),
                ('article_image', models.ImageField(upload_to='', verbose_name='Изображение статьи')),
                ('isStock', models.BooleanField(default=False)),
                ('body_editorjs', django_quill.fields.QuillField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Название категории продукта')),
                ('cat_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('cat_metadesc', models.CharField(blank=True, max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('cat_slug', models.CharField(default='slug2022-08-22 21:10:04.394433', max_length=200, verbose_name='URL')),
                ('cat_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('cat_desc', models.TextField(blank=True, verbose_name='Полное описание')),
                ('cat_image', models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Изображение категории')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cat_question_1', models.TextField(blank=True, default='', verbose_name='Вопрос 1')),
                ('cat_question_2', models.TextField(blank=True, default='', verbose_name='Вопорос 2')),
                ('cat_answer_1', models.TextField(blank=True, default='', verbose_name='Ответ 1')),
                ('cat_answer_2', models.TextField(blank=True, default='', verbose_name='Ответ 2')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200, verbose_name='Название региона')),
                ('region_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('region_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('region_slug', models.CharField(default='region2022-08-22 21:10:04.396005', max_length=200, verbose_name='URL')),
                ('region_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('body_editorjs', django_quill.fields.QuillField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkt_name', models.CharField(max_length=200, verbose_name='Название пункта приема')),
                ('punkt_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('punkt_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('punkt_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('punkt_geo', models.CharField(default='55.659173,37.762848', max_length=300, verbose_name='Описание description')),
                ('punkt_image', models.ImageField(upload_to='', verbose_name='Изображение пункта')),
                ('body_editorjs', django_quill.fields.QuillField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privod.region')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('product_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('product_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена')),
                ('product_short_desc', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('product_desc', models.TextField(blank=True, verbose_name='Артикул')),
                ('product_image', models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Изображение продукта')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('body_editorjs', django_quill.fields.QuillField()),
                ('product_slug', models.CharField(default='product2022-08-22 21:10:04.395478', max_length=200, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privod.category')),
            ],
        ),
    ]
