# Generated by Django 4.0.6 on 2022-08-22 18:43

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2022-08-22 21:43:07.542401', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2022-08-22 21:43:07.541403', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2022-08-22 21:43:07.541403', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2022-08-22 21:43:07.542401', max_length=200, verbose_name='URL'),
        ),
    ]
