# Generated by Django 3.2.4 on 2023-02-17 13:01

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0002_alter_article_article_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=200, verbose_name='Название производителя')),
                ('manufacturer_title', models.CharField(max_length=200, verbose_name='Заголовок для Open Graph (og:title)')),
                ('manufacturer_metadesc', models.CharField(max_length=300, verbose_name='Описание для Open Graph (og:description)')),
                ('manufacturer_image', models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Логотип производителя')),
                ('manufacturer_desc', models.TextField(blank=True, verbose_name='Описание производителя')),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('manufacturer_slug', models.CharField(default='manufacturer2023-02-17 16:01:46.300301', max_length=200, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-17 16:01:46.301301', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-17 16:01:46.299301', max_length=200, verbose_name='URL'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='privod.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-17 16:01:46.300301', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-17 16:01:46.301301', max_length=200, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ManyToManyField(to='privod.Manufacturer'),
        ),
    ]
