# Generated by Django 3.2.4 on 2023-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0003_auto_20230217_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-17 16:52:37.277402', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-17 16:52:37.275402', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-02-17 16:52:37.276404', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, to='privod.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-17 16:52:37.276404', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-17 16:52:37.277402', max_length=200, verbose_name='URL'),
        ),
    ]
