# Generated by Django 3.2.4 on 2023-02-17 13:57

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0004_auto_20230217_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-17 16:57:02.275847', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-17 16:57:02.273840', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-02-17 16:57:02.274847', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='privod.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-17 16:57:02.274917', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-17 16:57:02.275847', max_length=200, verbose_name='URL'),
        ),
    ]
