# Generated by Django 3.2.4 on 2023-02-17 13:59

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0005_auto_20230217_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-02-17 16:59:41.674553', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-02-17 16:59:41.672554', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-02-17 16:59:41.673556', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-02-17 16:59:41.673556', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-02-17 16:59:41.674553', max_length=200, verbose_name='URL'),
        ),
    ]
