# Generated by Django 3.2.4 on 2023-10-02 17:07

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0006_auto_20230217_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body_editorjs',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='longdescription',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-10-02 20:07:38.773475', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-10-02 20:07:38.771457', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-10-02 20:07:38.772471', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-10-02 20:07:38.772471', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-10-02 20:07:38.774482', max_length=200, verbose_name='URL'),
        ),
    ]
