# Generated by Django 3.2.4 on 2023-10-18 15:24

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0007_auto_20231002_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='documentationfield',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-10-18 18:24:47.390139', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-10-18 18:24:47.388130', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-10-18 18:24:47.388130', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-10-18 18:24:47.389134', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-10-18 18:24:47.390139', max_length=200, verbose_name='URL'),
        ),
    ]
