# Generated by Django 3.2.4 on 2023-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0008_auto_20231018_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pin_main',
            field=models.BooleanField(default=False, verbose_name='Закрепить на главной странице'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-11-01 20:17:55.245072', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-11-01 20:17:55.243047', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-11-01 20:17:55.244059', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-11-01 20:17:55.244059', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='punkt_name',
            field=models.CharField(max_length=200, verbose_name='Название офиса'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-11-01 20:17:55.245072', max_length=200, verbose_name='URL'),
        ),
    ]
