# Generated by Django 3.2.4 on 2023-11-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0009_auto_20231101_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pin_main_first',
            field=models.BooleanField(default=False, verbose_name='Закрепить на главной странице в первом блоке'),
        ),
        migrations.AddField(
            model_name='category',
            name='pin_main_sec',
            field=models.BooleanField(default=False, verbose_name='Закрепить на главной странице во втором блоке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-11-01 21:05:06.113169', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-11-01 21:05:06.111140', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-11-01 21:05:06.111140', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-11-01 21:05:06.112155', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-11-01 21:05:06.113169', max_length=200, verbose_name='URL'),
        ),
    ]
