# Generated by Django 3.2.4 on 2023-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0011_auto_20231101_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview_image',
            field=models.ImageField(default='placeholder.jpg', upload_to='', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2023-11-01 21:28:09.445855', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2023-11-01 21:28:09.443857', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2023-11-01 21:28:09.443857', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2023-11-01 21:28:09.444854', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2023-11-01 21:28:09.445855', max_length=200, verbose_name='URL'),
        ),
    ]
