# Generated by Django 4.1.7 on 2024-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privod", "0012_auto_20231101_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="punkt",
            name="punkt_map_key",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Ключ карты Яндекс"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="article_slug",
            field=models.CharField(
                default="article2024-02-03 09:25:13.058462",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_slug",
            field=models.CharField(
                default="slug2024-02-03 09:25:13.056505",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="manufacturer_slug",
            field=models.CharField(
                default="manufacturer2024-02-03 09:25:13.056998",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=models.CharField(
                default="product2024-02-03 09:25:13.057345",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_slug",
            field=models.CharField(
                default="region2024-02-03 09:25:13.058785",
                max_length=200,
                verbose_name="URL",
            ),
        ),
    ]
