# Generated by Django 4.1.7 on 2024-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privod", "0013_punkt_punkt_map_key_alter_article_article_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producttag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(max_length=200, verbose_name="Название тега"),
                ),
                (
                    "tag_title",
                    models.CharField(
                        max_length=200,
                        verbose_name="Заголовок для Open Graph (og:title)",
                    ),
                ),
                (
                    "tag_metadesc",
                    models.CharField(
                        max_length=300,
                        verbose_name="Описание для Open Graph (og:description)",
                    ),
                ),
                (
                    "tag_short_desc",
                    models.TextField(blank=True, verbose_name="Короткое описание"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="article_slug",
            field=models.CharField(
                default="article2024-02-12 19:17:00.548958",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_slug",
            field=models.CharField(
                default="slug2024-02-12 19:17:00.546276",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="manufacturer_slug",
            field=models.CharField(
                default="manufacturer2024-02-12 19:17:00.546797",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=models.CharField(
                default="product2024-02-12 19:17:00.547398",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_slug",
            field=models.CharField(
                default="region2024-02-12 19:17:00.549951",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_tag",
            field=models.ManyToManyField(blank=True, to="privod.producttag"),
        ),
    ]
