# Generated by Django 4.1.7 on 2024-02-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privod", "0014_producttag_alter_article_article_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttag",
            name="tag_slug",
            field=models.CharField(
                default="tag2024-02-12 19:27:18.186917",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="article_slug",
            field=models.CharField(
                default="article2024-02-12 19:27:18.188723",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_slug",
            field=models.CharField(
                default="slug2024-02-12 19:27:18.186116",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="manufacturer_slug",
            field=models.CharField(
                default="manufacturer2024-02-12 19:27:18.186633",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=models.CharField(
                default="product2024-02-12 19:27:18.187313",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_slug",
            field=models.CharField(
                default="region2024-02-12 19:27:18.189715",
                max_length=200,
                verbose_name="URL",
            ),
        ),
    ]
