# Generated by Django 4.1.7 on 2024-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privod", "0016_remove_category_cat_desc_category_cat_desccript_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_slug",
            field=models.CharField(
                default="article2024-02-12 19:58:17.086002",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_slug",
            field=models.CharField(
                default="slug2024-02-12 19:58:17.083317",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="manufacturer_slug",
            field=models.CharField(
                default="manufacturer2024-02-12 19:58:17.083862",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=models.CharField(
                default="product2024-02-12 19:58:17.084475",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="tag_slug",
            field=models.CharField(
                default="tag2024-02-12 19:58:17.084148",
                max_length=200,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_slug",
            field=models.CharField(
                default="region2024-02-12 19:58:17.087108",
                max_length=200,
                verbose_name="URL",
            ),
        ),
    ]
