# Generated by Django 4.2.5 on 2024-02-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privod', '0018_manufacturer_manufacturer_big_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2024-02-20 23:57:33.993394', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2024-02-20 23:57:33.990402', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_slug',
            field=models.CharField(default='manufacturer2024-02-20 23:57:33.990402', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default='product2024-02-20 23:57:33.991400', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tag_slug',
            field=models.CharField(default='tag2024-02-20 23:57:33.991400', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2024-02-20 23:57:33.993394', max_length=200, verbose_name='URL'),
        ),
    ]
